Repository fujaba/fulib, pull requests merged in 2020-09, with the labels that each got.

#62 Improve import(...) syntax
  src/main/antlr/FulibClass.g4
  src/main/java/org/fulib/parser/FragmentMapBuilder.java
  src/main/java/org/fulib/util/AbstractGenerator4ClassFile.java
  src/main/java/org/fulib/util/Generator4ClassFile.java
  src/main/resources/org/fulib/templates/method.stg
  src/test/java/org/fulib/generator/FMethodTest.java
Labels: enhancement

#63 Fix removal of PropertyChange members
  src/main/java/org/fulib/util/Generator4ClassFile.java
Labels: bug

#61 Add ClassModelManager.haveRole aliases for associate
  src/main/java/org/fulib/builder/ClassModelManager.java
Labels: feature

#64 Generated JavaDocs
  .palantir/revapi.yml
  src/gen/java/org/fulib/classmodel/GenModel.java
  src/main/antlr/FulibClass.g4
  src/main/java/org/fulib/classmodel/AssocRole.java
  src/main/java/org/fulib/classmodel/Attribute.java
  src/main/java/org/fulib/classmodel/ClassModel.java
  src/main/java/org/fulib/classmodel/Clazz.java
  src/main/java/org/fulib/classmodel/FMethod.java
  src/main/java/org/fulib/classmodel/classModel.yaml
  src/main/java/org/fulib/parser/FragmentMapBuilder.java
  src/main/resources/org/fulib/templates/associations.bean.stg
  src/main/resources/org/fulib/templates/associations.javafx.stg
  src/main/resources/org/fulib/templates/associations.pojo.stg
  src/main/resources/org/fulib/templates/attributes.bean.stg
  src/main/resources/org/fulib/templates/attributes.javafx.stg
  src/main/resources/org/fulib/templates/attributes.pojo.stg
  src/main/resources/org/fulib/templates/javadoc.stg
Labels: feature

#65 Group property methods and static fields together
  src/main/java/org/fulib/classmodel/FMethod.java
  src/main/java/org/fulib/classmodel/FileFragmentMap.java
  src/main/java/org/fulib/parser/FragmentMapBuilder.java
  src/main/java/org/fulib/util/AbstractGenerator4ClassFile.java
  src/main/java/org/fulib/util/Generator4TableClassFile.java
  src/main/java/org/fulib/util/Validator.java
  src/main/resources/org/fulib/templates/associations.pojo.stg
  src/main/resources/org/fulib/templates/attributes.pojo.stg
  src/test/java/org/fulib/util/ValidatorTest.java
Labels: enhancement

#67 Use Markdown for generated table toString
  src/main/resources/org/fulib/templates/tables/members.stg
  src/test/java/org/fulib/generator/TablesTest.java
Labels: enhancement

#69 Fix leading fragment whitespace
  src/main/java/org/fulib/classmodel/FileFragmentMap.java
Labels: bug

#68 Transform property constants to uppercase
  src/main/java/org/fulib/classmodel/AssocRole.java
  src/main/java/org/fulib/classmodel/Attribute.java
  src/main/java/org/fulib/classmodel/ClassModel.java
  src/main/java/org/fulib/classmodel/Clazz.java
  src/main/java/org/fulib/classmodel/CodeFragment.java
  src/main/java/org/fulib/classmodel/CompoundFragment.java
  src/main/java/org/fulib/classmodel/FMethod.java
  src/main/java/org/fulib/classmodel/FileFragmentMap.java
  src/main/java/org/fulib/classmodel/Fragment.java
  src/main/java/org/fulib/util/AbstractGenerator4ClassFile.java
  src/main/java/org/fulib/util/FulibStringRenderer.java
  src/main/java/org/fulib/util/Generator4ClassFile.java
  src/main/resources/org/fulib/templates/associations.bean.stg
  src/main/resources/org/fulib/templates/associations.javafx.stg
  src/main/resources/org/fulib/templates/associations.pojo.stg
  src/main/resources/org/fulib/templates/attributes.bean.stg
  src/main/resources/org/fulib/templates/attributes.javafx.stg
  src/main/resources/org/fulib/templates/attributes.pojo.stg
  src/test/java/org/fulib/util/StringRendererTest.java
  test/doc/images/studyRightObjects.png
  test/src/main/java/de/uniks/studyright/Room.java
  test/src/main/java/de/uniks/studyright/Student.java
  test/src/main/java/de/uniks/studyright/University.java
  test/src/main/java/de/uniks/studyright/classDiagram.png
Labels: enhancement

#72 Check for syntax errors in FMethod.setDeclaration
  src/main/java/org/fulib/classmodel/FMethod.java
  src/main/java/org/fulib/parser/FulibErrorHandler.java
  src/test/java/org/fulib/classmodel/FMethodTest.java
Labels: enhancement

#73 Add FMethod.getId
  src/main/java/org/fulib/classmodel/AssocRole.java
  src/main/java/org/fulib/classmodel/Attribute.java
  src/main/java/org/fulib/classmodel/FMethod.java
Labels: enhancement
